ALTER TABLE `SNAPSHOT` ADD `COUNT_MOUSE_CLICK` INT NOT NULL COMMENT 'Count mouse click';
ALTER TABLE `SNAPSHOT` ADD `COUNT_KEYBOARD_CLICK` INT NOT NULL COMMENT 'Count keyboard click';
ALTER TABLE `SNAPSHOT` ADD `TIME_INTERVAL` INT NOT NULL COMMENT 'Time interval between snapshots';