CREATE TABLE IF NOT EXISTS `TEST` (
  `ID` int(11)  NOT NULL AUTO_INCREMENT COMMENT 'Id test',
  `NOTE` varchar(255) NOT NULL COMMENT 'test note',
  PRIMARY KEY  (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='Table test';