ALTER TABLE `CLIENT_COMPANY` ADD `STATUS` varchar(128) NOT NULL COMMENT 'Status for company';
ALTER TABLE `DEPARTMENT` ADD `STATUS` varchar(128) NOT NULL COMMENT 'Status for department';
ALTER TABLE `PROJECT` ADD `STATUS` varchar(128) NOT NULL COMMENT 'Status for project';
ALTER TABLE `CLIENT_COMPANY` ADD `ID_OWNER` int(11) NOT NULL COMMENT 'Id owner';
ALTER TABLE `CLIENT_COMPANY`
ADD CONSTRAINT `client_company_owner_fk1`
  FOREIGN KEY (ID_OWNER)
  REFERENCES USER(ID);
